// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonSupersededRuns = `-- name: AbandonSupersededRuns :many
UPDATE agent_runs r SET status = 'abandoned', error_code = 'superseded', updated_at = now()
WHERE r.subject_type = $1 AND r.subject_id = $2 AND r.status = 'running'
  AND EXISTS (SELECT 1 FROM agent_runs n
              WHERE n.subject_type = r.subject_type AND n.subject_id = r.subject_id
                AND n.started_at > r.started_at)
RETURNING r.id
`

type AbandonSupersededRunsParams struct {
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
}

// A newer run for the same subject exists: the older running ones were redelivered away (ack_wait
// expired, worker died). Order-independent, so it runs after every run.started.
func (q *Queries) AbandonSupersededRuns(ctx context.Context, arg AbandonSupersededRunsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, abandonSupersededRuns, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentSummary = `-- name: AgentSummary :many
SELECT agent, model, coalesce(sum(llm_calls), 0)::bigint AS calls,
       coalesce(avg(duration_ms), 0)::bigint AS avg_ms
FROM agent_steps
WHERE at >= $1::timestamptz AND at < $2::timestamptz
  AND status IN ('succeeded', 'failed')
GROUP BY agent, model
ORDER BY agent, model
`

type AgentSummaryParams struct {
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

type AgentSummaryRow struct {
	Agent string `json:"agent"`
	Model string `json:"model"`
	Calls int64  `json:"calls"`
	AvgMs int64  `json:"avg_ms"`
}

func (q *Queries) AgentSummary(ctx context.Context, arg AgentSummaryParams) ([]AgentSummaryRow, error) {
	rows, err := q.db.Query(ctx, agentSummary, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSummaryRow
	for rows.Next() {
		var i AgentSummaryRow
		if err := rows.Scan(
			&i.Agent,
			&i.Model,
			&i.Calls,
			&i.AvgMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, firm_id, client_company_id, workflow, subject_type, subject_id, status, error_code, delivery_attempt, trace_id, plan, budget, steps, llm_calls, response_cache_hits, input_tokens, output_tokens, cost_micro_usd, started_at, finished_at, created_at, updated_at FROM agent_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Workflow,
		&i.SubjectType,
		&i.SubjectID,
		&i.Status,
		&i.ErrorCode,
		&i.DeliveryAttempt,
		&i.TraceID,
		&i.Plan,
		&i.Budget,
		&i.Steps,
		&i.LlmCalls,
		&i.ResponseCacheHits,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicroUsd,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT id, firm_id, run_id, seq, node_id, depends_on, agent, action, kind, status, attempt, at, duration_ms, model, prompt_id, prompt_version, input_tokens, output_tokens, cache_read_input_tokens, cache_creation_input_tokens, cost_micro_usd, response_cache_hit, llm_calls, message_key, message_args, error_code, subject_type, subject_id, client_company_id, created_at, updated_at FROM agent_steps WHERE run_id = $1 ORDER BY seq
`

func (q *Queries) ListRunSteps(ctx context.Context, runID uuid.UUID) ([]AgentStep, error) {
	rows, err := q.db.Query(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentStep
	for rows.Next() {
		var i AgentStep
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.RunID,
			&i.Seq,
			&i.NodeID,
			&i.DependsOn,
			&i.Agent,
			&i.Action,
			&i.Kind,
			&i.Status,
			&i.Attempt,
			&i.At,
			&i.DurationMs,
			&i.Model,
			&i.PromptID,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadInputTokens,
			&i.CacheCreationInputTokens,
			&i.CostMicroUsd,
			&i.ResponseCacheHit,
			&i.LlmCalls,
			&i.MessageKey,
			&i.MessageArgs,
			&i.ErrorCode,
			&i.SubjectType,
			&i.SubjectID,
			&i.ClientCompanyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, firm_id, client_company_id, workflow, subject_type, subject_id, status, error_code, delivery_attempt, trace_id, plan, budget, steps, llm_calls, response_cache_hits, input_tokens, output_tokens, cost_micro_usd, started_at, finished_at, created_at, updated_at FROM agent_runs
WHERE ($1::text IS NULL OR subject_type = $1::text)
  AND ($2::text IS NULL OR subject_id = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::timestamptz IS NULL
       OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListRunsParams struct {
	SubjectType     pgtype.Text        `json:"subject_type"`
	SubjectID       pgtype.Text        `json:"subject_id"`
	Status          pgtype.Text        `json:"status"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        uuid.NullUUID      `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.SubjectType,
		arg.SubjectID,
		arg.Status,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientCompanyID,
			&i.Workflow,
			&i.SubjectType,
			&i.SubjectID,
			&i.Status,
			&i.ErrorCode,
			&i.DeliveryAttempt,
			&i.TraceID,
			&i.Plan,
			&i.Budget,
			&i.Steps,
			&i.LlmCalls,
			&i.ResponseCacheHits,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicroUsd,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentRuns = `-- name: RecentRuns :many
SELECT id, firm_id, client_company_id, workflow, subject_type, subject_id, status, error_code, delivery_attempt, trace_id, plan, budget, steps, llm_calls, response_cache_hits, input_tokens, output_tokens, cost_micro_usd, started_at, finished_at, created_at, updated_at FROM agent_runs WHERE updated_at > $1 ORDER BY updated_at DESC LIMIT $2
`

type RecentRunsParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	PageLimit int32              `json:"page_limit"`
}

func (q *Queries) RecentRuns(ctx context.Context, arg RecentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, recentRuns, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientCompanyID,
			&i.Workflow,
			&i.SubjectType,
			&i.SubjectID,
			&i.Status,
			&i.ErrorCode,
			&i.DeliveryAttempt,
			&i.TraceID,
			&i.Plan,
			&i.Budget,
			&i.Steps,
			&i.LlmCalls,
			&i.ResponseCacheHits,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicroUsd,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentSteps = `-- name: RecentSteps :many
SELECT id, firm_id, run_id, seq, node_id, depends_on, agent, action, kind, status, attempt, at, duration_ms, model, prompt_id, prompt_version, input_tokens, output_tokens, cache_read_input_tokens, cache_creation_input_tokens, cost_micro_usd, response_cache_hit, llm_calls, message_key, message_args, error_code, subject_type, subject_id, client_company_id, created_at, updated_at FROM agent_steps WHERE updated_at > $1 ORDER BY updated_at DESC LIMIT $2
`

type RecentStepsParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	PageLimit int32              `json:"page_limit"`
}

// SSE backfill: steps changed after @since (Last-Event-ID) or the latest ones.
func (q *Queries) RecentSteps(ctx context.Context, arg RecentStepsParams) ([]AgentStep, error) {
	rows, err := q.db.Query(ctx, recentSteps, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentStep
	for rows.Next() {
		var i AgentStep
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.RunID,
			&i.Seq,
			&i.NodeID,
			&i.DependsOn,
			&i.Agent,
			&i.Action,
			&i.Kind,
			&i.Status,
			&i.Attempt,
			&i.At,
			&i.DurationMs,
			&i.Model,
			&i.PromptID,
			&i.PromptVersion,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadInputTokens,
			&i.CacheCreationInputTokens,
			&i.CostMicroUsd,
			&i.ResponseCacheHit,
			&i.LlmCalls,
			&i.MessageKey,
			&i.MessageArgs,
			&i.ErrorCode,
			&i.SubjectType,
			&i.SubjectID,
			&i.ClientCompanyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runSummary = `-- name: RunSummary :one
SELECT count(*)::bigint AS runs,
       count(*) FILTER (WHERE status = 'running')::bigint AS running,
       count(DISTINCT subject_id) FILTER (WHERE subject_type = 'document')::bigint AS documents,
       coalesce(sum(llm_calls), 0)::bigint AS llm_calls,
       coalesce(sum(response_cache_hits), 0)::bigint AS response_cache_hits,
       coalesce(sum(cost_micro_usd), 0)::bigint AS cost_micro_usd
FROM agent_runs
WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz
`

type RunSummaryParams struct {
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

type RunSummaryRow struct {
	Runs              int64 `json:"runs"`
	Running           int64 `json:"running"`
	Documents         int64 `json:"documents"`
	LlmCalls          int64 `json:"llm_calls"`
	ResponseCacheHits int64 `json:"response_cache_hits"`
	CostMicroUsd      int64 `json:"cost_micro_usd"`
}

func (q *Queries) RunSummary(ctx context.Context, arg RunSummaryParams) (RunSummaryRow, error) {
	row := q.db.QueryRow(ctx, runSummary, arg.DayStart, arg.DayEnd)
	var i RunSummaryRow
	err := row.Scan(
		&i.Runs,
		&i.Running,
		&i.Documents,
		&i.LlmCalls,
		&i.ResponseCacheHits,
		&i.CostMicroUsd,
	)
	return i, err
}

const upsertRunFinished = `-- name: UpsertRunFinished :exec
INSERT INTO agent_runs (id, firm_id, subject_type, subject_id, status, error_code, steps, llm_calls,
                        response_cache_hits, input_tokens, output_tokens, cost_micro_usd, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE
  SET status = EXCLUDED.status, error_code = EXCLUDED.error_code, steps = EXCLUDED.steps,
      llm_calls = EXCLUDED.llm_calls, response_cache_hits = EXCLUDED.response_cache_hits,
      input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens,
      cost_micro_usd = EXCLUDED.cost_micro_usd, finished_at = EXCLUDED.finished_at, updated_at = now()
`

type UpsertRunFinishedParams struct {
	ID                uuid.UUID          `json:"id"`
	FirmID            uuid.UUID          `json:"firm_id"`
	SubjectType       string             `json:"subject_type"`
	SubjectID         string             `json:"subject_id"`
	Status            string             `json:"status"`
	ErrorCode         string             `json:"error_code"`
	Steps             int32              `json:"steps"`
	LlmCalls          int32              `json:"llm_calls"`
	ResponseCacheHits int32              `json:"response_cache_hits"`
	InputTokens       int64              `json:"input_tokens"`
	OutputTokens      int64              `json:"output_tokens"`
	CostMicroUsd      int64              `json:"cost_micro_usd"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpsertRunFinished(ctx context.Context, arg UpsertRunFinishedParams) error {
	_, err := q.db.Exec(ctx, upsertRunFinished,
		arg.ID,
		arg.FirmID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Status,
		arg.ErrorCode,
		arg.Steps,
		arg.LlmCalls,
		arg.ResponseCacheHits,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMicroUsd,
		arg.FinishedAt,
	)
	return err
}

const upsertRunStarted = `-- name: UpsertRunStarted :exec
INSERT INTO agent_runs (id, firm_id, client_company_id, workflow, subject_type, subject_id, status,
                        delivery_attempt, trace_id, plan, budget, started_at)
VALUES ($1, $2, $3, $4, $5, $6, 'running',
        $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE
  SET client_company_id = EXCLUDED.client_company_id, workflow = EXCLUDED.workflow,
      delivery_attempt = EXCLUDED.delivery_attempt, trace_id = EXCLUDED.trace_id, plan = EXCLUDED.plan,
      budget = EXCLUDED.budget, started_at = EXCLUDED.started_at, updated_at = now()
`

type UpsertRunStartedParams struct {
	ID              uuid.UUID          `json:"id"`
	FirmID          uuid.UUID          `json:"firm_id"`
	ClientCompanyID uuid.NullUUID      `json:"client_company_id"`
	Workflow        string             `json:"workflow"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       string             `json:"subject_id"`
	DeliveryAttempt int32              `json:"delivery_attempt"`
	TraceID         string             `json:"trace_id"`
	Plan            []byte             `json:"plan"`
	Budget          []byte             `json:"budget"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
}

// Never changes status: a run.finished processed earlier keeps its final status.
func (q *Queries) UpsertRunStarted(ctx context.Context, arg UpsertRunStartedParams) error {
	_, err := q.db.Exec(ctx, upsertRunStarted,
		arg.ID,
		arg.FirmID,
		arg.ClientCompanyID,
		arg.Workflow,
		arg.SubjectType,
		arg.SubjectID,
		arg.DeliveryAttempt,
		arg.TraceID,
		arg.Plan,
		arg.Budget,
		arg.StartedAt,
	)
	return err
}

const upsertStep = `-- name: UpsertStep :exec
INSERT INTO agent_steps (id, firm_id, run_id, seq, node_id, depends_on, agent, action, kind, status, attempt,
                         at, duration_ms, model, prompt_id, prompt_version, input_tokens, output_tokens,
                         cache_read_input_tokens, cache_creation_input_tokens, cost_micro_usd,
                         response_cache_hit, llm_calls, message_key, message_args, error_code, subject_type,
                         subject_id, client_company_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        $12, $13, $14, $15, $16, $17, $18,
        $19, $20, $21,
        $22, $23, $24, $25, $26, $27,
        $28, $29)
ON CONFLICT (id) DO UPDATE
  SET seq = EXCLUDED.seq, status = EXCLUDED.status, at = EXCLUDED.at, duration_ms = EXCLUDED.duration_ms,
      depends_on = EXCLUDED.depends_on, model = EXCLUDED.model, prompt_id = EXCLUDED.prompt_id,
      prompt_version = EXCLUDED.prompt_version, input_tokens = EXCLUDED.input_tokens,
      output_tokens = EXCLUDED.output_tokens, cache_read_input_tokens = EXCLUDED.cache_read_input_tokens,
      cache_creation_input_tokens = EXCLUDED.cache_creation_input_tokens,
      cost_micro_usd = EXCLUDED.cost_micro_usd, response_cache_hit = EXCLUDED.response_cache_hit,
      llm_calls = EXCLUDED.llm_calls, message_key = EXCLUDED.message_key,
      message_args = EXCLUDED.message_args, error_code = EXCLUDED.error_code, updated_at = now()
  WHERE agent_steps.seq < EXCLUDED.seq
`

type UpsertStepParams struct {
	ID                       uuid.UUID          `json:"id"`
	FirmID                   uuid.UUID          `json:"firm_id"`
	RunID                    uuid.UUID          `json:"run_id"`
	Seq                      int64              `json:"seq"`
	NodeID                   string             `json:"node_id"`
	DependsOn                []string           `json:"depends_on"`
	Agent                    string             `json:"agent"`
	Action                   string             `json:"action"`
	Kind                     string             `json:"kind"`
	Status                   string             `json:"status"`
	Attempt                  int32              `json:"attempt"`
	At                       pgtype.Timestamptz `json:"at"`
	DurationMs               int64              `json:"duration_ms"`
	Model                    string             `json:"model"`
	PromptID                 string             `json:"prompt_id"`
	PromptVersion            int32              `json:"prompt_version"`
	InputTokens              int64              `json:"input_tokens"`
	OutputTokens             int64              `json:"output_tokens"`
	CacheReadInputTokens     int64              `json:"cache_read_input_tokens"`
	CacheCreationInputTokens int64              `json:"cache_creation_input_tokens"`
	CostMicroUsd             int64              `json:"cost_micro_usd"`
	ResponseCacheHit         bool               `json:"response_cache_hit"`
	LlmCalls                 int32              `json:"llm_calls"`
	MessageKey               string             `json:"message_key"`
	MessageArgs              []byte             `json:"message_args"`
	ErrorCode                string             `json:"error_code"`
	SubjectType              string             `json:"subject_type"`
	SubjectID                string             `json:"subject_id"`
	ClientCompanyID          uuid.NullUUID      `json:"client_company_id"`
}

// For one step_id the event with the highest seq wins (contract 4.1).
func (q *Queries) UpsertStep(ctx context.Context, arg UpsertStepParams) error {
	_, err := q.db.Exec(ctx, upsertStep,
		arg.ID,
		arg.FirmID,
		arg.RunID,
		arg.Seq,
		arg.NodeID,
		arg.DependsOn,
		arg.Agent,
		arg.Action,
		arg.Kind,
		arg.Status,
		arg.Attempt,
		arg.At,
		arg.DurationMs,
		arg.Model,
		arg.PromptID,
		arg.PromptVersion,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadInputTokens,
		arg.CacheCreationInputTokens,
		arg.CostMicroUsd,
		arg.ResponseCacheHit,
		arg.LlmCalls,
		arg.MessageKey,
		arg.MessageArgs,
		arg.ErrorCode,
		arg.SubjectType,
		arg.SubjectID,
		arg.ClientCompanyID,
	)
	return err
}
