// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_companies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClientCompany = `-- name: CreateClientCompany :one
INSERT INTO client_companies (firm_id, name, name_ar, trn, tin, emirate)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, firm_id, name, name_ar, trn, tin, emirate, status, created_at, updated_at
`

type CreateClientCompanyParams struct {
	FirmID  uuid.UUID   `json:"firm_id"`
	Name    string      `json:"name"`
	NameAr  string      `json:"name_ar"`
	Trn     pgtype.Text `json:"trn"`
	Tin     pgtype.Text `json:"tin"`
	Emirate pgtype.Text `json:"emirate"`
}

func (q *Queries) CreateClientCompany(ctx context.Context, arg CreateClientCompanyParams) (ClientCompany, error) {
	row := q.db.QueryRow(ctx, createClientCompany,
		arg.FirmID,
		arg.Name,
		arg.NameAr,
		arg.Trn,
		arg.Tin,
		arg.Emirate,
	)
	var i ClientCompany
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.NameAr,
		&i.Trn,
		&i.Tin,
		&i.Emirate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientCompany = `-- name: GetClientCompany :one
SELECT id, firm_id, name, name_ar, trn, tin, emirate, status, created_at, updated_at FROM client_companies WHERE id = $1
`

func (q *Queries) GetClientCompany(ctx context.Context, id uuid.UUID) (ClientCompany, error) {
	row := q.db.QueryRow(ctx, getClientCompany, id)
	var i ClientCompany
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.NameAr,
		&i.Trn,
		&i.Tin,
		&i.Emirate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveClientCompanyRefs = `-- name: ListActiveClientCompanyRefs :many
SELECT id, name, name_ar, trn FROM client_companies WHERE status = 'active' ORDER BY name, id LIMIT 500
`

type ListActiveClientCompanyRefsRow struct {
	ID     uuid.UUID   `json:"id"`
	Name   string      `json:"name"`
	NameAr string      `json:"name_ar"`
	Trn    pgtype.Text `json:"trn"`
}

func (q *Queries) ListActiveClientCompanyRefs(ctx context.Context) ([]ListActiveClientCompanyRefsRow, error) {
	rows, err := q.db.Query(ctx, listActiveClientCompanyRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveClientCompanyRefsRow
	for rows.Next() {
		var i ListActiveClientCompanyRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameAr,
			&i.Trn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientCompanies = `-- name: ListClientCompanies :many
SELECT c.id, c.firm_id, c.name, c.name_ar, c.trn, c.tin, c.emirate, c.status, c.created_at, c.updated_at,
       coalesce(d.total, 0)::bigint AS documents_total,
       coalesce(d.needs_review, 0)::bigint AS documents_needs_review
FROM client_companies c
LEFT JOIN LATERAL (
  SELECT count(*) AS total, count(*) FILTER (WHERE status = 'needs_review') AS needs_review
  FROM documents WHERE documents.client_company_id = c.id
) d ON true
WHERE ($1::text = 'all' OR c.status = $1::text)
  AND ($2::text IS NULL
       OR c.name ILIKE $2::text
       OR c.name_ar ILIKE $2::text
       OR c.trn LIKE $2::text)
  AND ($3::text IS NULL
       OR (c.name, c.id) > ($3::text, $4::uuid))
ORDER BY c.name, c.id
LIMIT $5
`

type ListClientCompaniesParams struct {
	Status    string        `json:"status"`
	Pattern   pgtype.Text   `json:"pattern"`
	AfterName pgtype.Text   `json:"after_name"`
	AfterID   uuid.NullUUID `json:"after_id"`
	PageLimit int32         `json:"page_limit"`
}

type ListClientCompaniesRow struct {
	ID                   uuid.UUID          `json:"id"`
	FirmID               uuid.UUID          `json:"firm_id"`
	Name                 string             `json:"name"`
	NameAr               string             `json:"name_ar"`
	Trn                  pgtype.Text        `json:"trn"`
	Tin                  pgtype.Text        `json:"tin"`
	Emirate              pgtype.Text        `json:"emirate"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DocumentsTotal       int64              `json:"documents_total"`
	DocumentsNeedsReview int64              `json:"documents_needs_review"`
}

// status: 'active' | 'archived' | 'all'. pattern: an escaped ILIKE pattern ('%foo%') or NULL.
// Keyset on (name, id); after_name/after_id come from the previous page's last row.
func (q *Queries) ListClientCompanies(ctx context.Context, arg ListClientCompaniesParams) ([]ListClientCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listClientCompanies,
		arg.Status,
		arg.Pattern,
		arg.AfterName,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientCompaniesRow
	for rows.Next() {
		var i ListClientCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.Name,
			&i.NameAr,
			&i.Trn,
			&i.Tin,
			&i.Emirate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentsTotal,
			&i.DocumentsNeedsReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClientCompanyStatus = `-- name: SetClientCompanyStatus :one
UPDATE client_companies SET status = $1, updated_at = now() WHERE id = $2 RETURNING id, firm_id, name, name_ar, trn, tin, emirate, status, created_at, updated_at
`

type SetClientCompanyStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetClientCompanyStatus(ctx context.Context, arg SetClientCompanyStatusParams) (ClientCompany, error) {
	row := q.db.QueryRow(ctx, setClientCompanyStatus, arg.Status, arg.ID)
	var i ClientCompany
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.NameAr,
		&i.Trn,
		&i.Tin,
		&i.Emirate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientCompany = `-- name: UpdateClientCompany :one
UPDATE client_companies
SET name = $1, name_ar = $2, trn = $3, tin = $4, emirate = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, firm_id, name, name_ar, trn, tin, emirate, status, created_at, updated_at
`

type UpdateClientCompanyParams struct {
	Name    string      `json:"name"`
	NameAr  string      `json:"name_ar"`
	Trn     pgtype.Text `json:"trn"`
	Tin     pgtype.Text `json:"tin"`
	Emirate pgtype.Text `json:"emirate"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateClientCompany(ctx context.Context, arg UpdateClientCompanyParams) (ClientCompany, error) {
	row := q.db.QueryRow(ctx, updateClientCompany,
		arg.Name,
		arg.NameAr,
		arg.Trn,
		arg.Tin,
		arg.Emirate,
		arg.ID,
	)
	var i ClientCompany
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.NameAr,
		&i.Trn,
		&i.Tin,
		&i.Emirate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
