// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyDocumentExtracted = `-- name: ApplyDocumentExtracted :execrows
UPDATE documents
SET status = $1, status_reason = $2, kind = $3, direction = $4,
    language = $5, extraction_method = $6, review_reasons = $7,
    invoice_count = $8, latest_run_id = $9, updated_at = now()
WHERE id = $10 AND status IN ('uploaded', 'processing')
`

type ApplyDocumentExtractedParams struct {
	Status           string        `json:"status"`
	StatusReason     string        `json:"status_reason"`
	Kind             string        `json:"kind"`
	Direction        string        `json:"direction"`
	Language         string        `json:"language"`
	ExtractionMethod string        `json:"extraction_method"`
	ReviewReasons    []string      `json:"review_reasons"`
	InvoiceCount     int32         `json:"invoice_count"`
	RunID            uuid.NullUUID `json:"run_id"`
	ID               uuid.UUID     `json:"id"`
}

// First result wins; a redelivered or superseded run's result is a no-op (0 rows).
func (q *Queries) ApplyDocumentExtracted(ctx context.Context, arg ApplyDocumentExtractedParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyDocumentExtracted,
		arg.Status,
		arg.StatusReason,
		arg.Kind,
		arg.Direction,
		arg.Language,
		arg.ExtractionMethod,
		arg.ReviewReasons,
		arg.InvoiceCount,
		arg.RunID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyDocumentFailed = `-- name: ApplyDocumentFailed :execrows
UPDATE documents SET status = 'failed', status_reason = $1, latest_run_id = $2, updated_at = now()
WHERE id = $3 AND status IN ('uploaded', 'processing')
`

type ApplyDocumentFailedParams struct {
	Reason string        `json:"reason"`
	RunID  uuid.NullUUID `json:"run_id"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) ApplyDocumentFailed(ctx context.Context, arg ApplyDocumentFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyDocumentFailed, arg.Reason, arg.RunID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpDocumentPublishAttempt = `-- name: BumpDocumentPublishAttempt :one
UPDATE documents SET publish_attempts = publish_attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'uploaded' AND published_at IS NULL
RETURNING publish_attempts
`

func (q *Queries) BumpDocumentPublishAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpDocumentPublishAttempt, id)
	var publish_attempts int32
	err := row.Scan(&publish_attempts)
	return publish_attempts, err
}

const failUnpublishedDocument = `-- name: FailUnpublishedDocument :execrows
UPDATE documents SET status = 'failed', status_reason = 'publish_exhausted', updated_at = now()
WHERE id = $1 AND status = 'uploaded' AND published_at IS NULL
`

func (q *Queries) FailUnpublishedDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, failUnpublishedDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByHash = `-- name: GetDocumentByHash :one
SELECT id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at FROM documents WHERE client_company_id = $1 AND sha256 = $2
`

type GetDocumentByHashParams struct {
	ClientCompanyID uuid.UUID `json:"client_company_id"`
	Sha256          string    `json:"sha256"`
}

func (q *Queries) GetDocumentByHash(ctx context.Context, arg GetDocumentByHashParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByHash, arg.ClientCompanyID, arg.Sha256)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentInvoices = `-- name: ListDocumentInvoices :many
SELECT id, status, source_ordinal, extraction_confidence FROM invoices
WHERE document_id = $1
ORDER BY source_ordinal
`

type ListDocumentInvoicesRow struct {
	ID                   uuid.UUID      `json:"id"`
	Status               string         `json:"status"`
	SourceOrdinal        pgtype.Int4    `json:"source_ordinal"`
	ExtractionConfidence pgtype.Numeric `json:"extraction_confidence"`
}

func (q *Queries) ListDocumentInvoices(ctx context.Context, documentID uuid.NullUUID) ([]ListDocumentInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentInvoices, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentInvoicesRow
	for rows.Next() {
		var i ListDocumentInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SourceOrdinal,
			&i.ExtractionConfidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at FROM documents
WHERE ($1::uuid IS NULL OR client_company_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListDocumentsParams struct {
	ClientCompanyID uuid.NullUUID      `json:"client_company_id"`
	Status          pgtype.Text        `json:"status"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        uuid.NullUUID      `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.ClientCompanyID,
		arg.Status,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientCompanyID,
			&i.Sha256,
			&i.ObjectKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.StatusReason,
			&i.Kind,
			&i.Direction,
			&i.Language,
			&i.ExtractionMethod,
			&i.ReviewReasons,
			&i.InvoiceCount,
			&i.PublishAttempts,
			&i.PublishedAt,
			&i.ReprocessNonce,
			&i.LatestRunID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedDocuments = `-- name: ListUnpublishedDocuments :many
SELECT id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at FROM documents
WHERE status = 'uploaded' AND published_at IS NULL AND updated_at < now() - interval '1 minute'
ORDER BY updated_at
LIMIT 100
`

// Reconciler: committed but never acknowledged by JetStream (api-go died between commit and publish).
func (q *Queries) ListUnpublishedDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listUnpublishedDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientCompanyID,
			&i.Sha256,
			&i.ObjectKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.StatusReason,
			&i.Kind,
			&i.Direction,
			&i.Language,
			&i.ExtractionMethod,
			&i.ReviewReasons,
			&i.InvoiceCount,
			&i.PublishAttempts,
			&i.PublishedAt,
			&i.ReprocessNonce,
			&i.LatestRunID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDocument = `-- name: LockDocument :one
SELECT id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at FROM documents WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, lockDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDocumentProcessing = `-- name: MarkDocumentProcessing :execrows
UPDATE documents SET status = 'processing', latest_run_id = $1, updated_at = now()
WHERE id = $2 AND status IN ('uploaded', 'processing')
`

type MarkDocumentProcessingParams struct {
	RunID uuid.NullUUID `json:"run_id"`
	ID    uuid.UUID     `json:"id"`
}

// agent.run.started for a document subject. Never moves a terminal Document backwards.
func (q *Queries) MarkDocumentProcessing(ctx context.Context, arg MarkDocumentProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentProcessing, arg.RunID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentPublished = `-- name: MarkDocumentPublished :execrows
UPDATE documents SET published_at = now(), publish_attempts = publish_attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'uploaded' AND reprocess_nonce = $2 AND published_at IS NULL
`

type MarkDocumentPublishedParams struct {
	ID             uuid.UUID `json:"id"`
	ReprocessNonce string    `json:"reprocess_nonce"`
}

// Guarded by the nonce so a stale publish ack never marks a newer reprocess as published.
func (q *Queries) MarkDocumentPublished(ctx context.Context, arg MarkDocumentPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentPublished, arg.ID, arg.ReprocessNonce)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentUploaded = `-- name: MarkDocumentUploaded :one
UPDATE documents SET status = 'uploaded', status_reason = '', updated_at = now()
WHERE id = $1 AND status = 'pending_upload'
RETURNING id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at
`

func (q *Queries) MarkDocumentUploaded(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, markDocumentUploaded, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reattributeDocument = `-- name: ReattributeDocument :execrows
UPDATE documents SET client_company_id = $1, direction = $2, updated_at = now()
WHERE id = $3
`

type ReattributeDocumentParams struct {
	ClientCompanyID uuid.UUID `json:"client_company_id"`
	Direction       string    `json:"direction"`
	ID              uuid.UUID `json:"id"`
}

// document.attribution applier: direction is relative to the ClientCompany, so it moves with it.
func (q *Queries) ReattributeDocument(ctx context.Context, arg ReattributeDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, reattributeDocument, arg.ClientCompanyID, arg.Direction, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectDocument = `-- name: RejectDocument :one
UPDATE documents SET status = 'rejected', status_reason = $1, updated_at = now()
WHERE id = $2 AND status = 'pending_upload'
RETURNING id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at
`

type RejectDocumentParams struct {
	Reason string    `json:"reason"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RejectDocument(ctx context.Context, arg RejectDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, rejectDocument, arg.Reason, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reprocessDocument = `-- name: ReprocessDocument :one
UPDATE documents
SET status = 'uploaded', status_reason = '', kind = '', direction = '', language = '', extraction_method = '',
    review_reasons = '{}', reprocess_nonce = gen_random_uuid()::text, published_at = NULL,
    publish_attempts = 0, updated_at = now()
WHERE id = $1
  AND (status IN ('failed', 'not_invoice') OR (status = 'needs_review' AND invoice_count = 0))
RETURNING id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at
`

func (q *Queries) ReprocessDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, reprocessDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetStuckDocuments = `-- name: ResetStuckDocuments :many
UPDATE documents d
SET status = 'uploaded', status_reason = '', reprocess_nonce = gen_random_uuid()::text,
    published_at = NULL, publish_attempts = 0, updated_at = now()
WHERE d.status = 'processing' AND d.updated_at < now() - interval '30 minutes'
  AND NOT EXISTS (
    SELECT 1 FROM agent_runs r
    WHERE r.subject_type = 'document' AND r.subject_id = d.id::text AND r.status = 'running'
      AND r.updated_at > now() - interval '30 minutes')
RETURNING d.id
`

// A Document processing for 30 minutes with no running run lost its message: back to uploaded with a
// new nonce, so the unpublished path above republishes it.
func (q *Queries) ResetStuckDocuments(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, resetStuckDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPendingDocument = `-- name: UpsertPendingDocument :one
INSERT INTO documents (id, firm_id, client_company_id, sha256, object_key, filename, content_type,
                       size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9)
ON CONFLICT (firm_id, client_company_id, sha256) DO UPDATE
  SET filename = EXCLUDED.filename, content_type = EXCLUDED.content_type, size_bytes = EXCLUDED.size_bytes,
      uploaded_by = EXCLUDED.uploaded_by, status = 'pending_upload', status_reason = '',
      reprocess_nonce = gen_random_uuid()::text, published_at = NULL, publish_attempts = 0,
      updated_at = now()
  WHERE documents.status IN ('pending_upload', 'rejected')
RETURNING id, firm_id, client_company_id, sha256, object_key, filename, content_type, size_bytes, status, status_reason, kind, direction, language, extraction_method, review_reasons, invoice_count, publish_attempts, published_at, reprocess_nonce, latest_run_id, uploaded_by, created_at, updated_at
`

type UpsertPendingDocumentParams struct {
	ID              uuid.UUID `json:"id"`
	FirmID          uuid.UUID `json:"firm_id"`
	ClientCompanyID uuid.UUID `json:"client_company_id"`
	Sha256          string    `json:"sha256"`
	ObjectKey       string    `json:"object_key"`
	Filename        string    `json:"filename"`
	ContentType     string    `json:"content_type"`
	SizeBytes       int64     `json:"size_bytes"`
	UploadedBy      string    `json:"uploaded_by"`
}

// Inserts a pending_upload row, or resets an existing pending_upload/rejected row with the same
// (firm, client company, sha256). Returns no row (pgx.ErrNoRows) when the existing row is in any
// other status: the caller then reports deduplicated=true (spec 5.1 step 2). object_key must be
// documents.ObjectKey(firm_id, id); the documents_object_key_shape CHECK rejects anything else.
func (q *Queries) UpsertPendingDocument(ctx context.Context, arg UpsertPendingDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, upsertPendingDocument,
		arg.ID,
		arg.FirmID,
		arg.ClientCompanyID,
		arg.Sha256,
		arg.ObjectKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.Sha256,
		&i.ObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.StatusReason,
		&i.Kind,
		&i.Direction,
		&i.Language,
		&i.ExtractionMethod,
		&i.ReviewReasons,
		&i.InvoiceCount,
		&i.PublishAttempts,
		&i.PublishedAt,
		&i.ReprocessNonce,
		&i.LatestRunID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
