// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: firms.sql

package sqlc

import (
	"context"
)

const firmByOrg = `-- name: FirmByOrg :one
SELECT id, zitadel_org_id, name, brand_color, created_at, updated_at FROM firms WHERE zitadel_org_id = $1
`

func (q *Queries) FirmByOrg(ctx context.Context, zitadelOrgID string) (Firm, error) {
	row := q.db.QueryRow(ctx, firmByOrg, zitadelOrgID)
	var i Firm
	err := row.Scan(
		&i.ID,
		&i.ZitadelOrgID,
		&i.Name,
		&i.BrandColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
