// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: firm_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFirm = `-- name: GetFirm :one
SELECT id, name, brand_color, updated_at FROM firms WHERE id = $1
`

type GetFirmRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	BrandColor pgtype.Text        `json:"brand_color"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFirm(ctx context.Context, id uuid.UUID) (GetFirmRow, error) {
	row := q.db.QueryRow(ctx, getFirm, id)
	var i GetFirmRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BrandColor,
		&i.UpdatedAt,
	)
	return i, err
}

const listFirmIDs = `-- name: ListFirmIDs :many
SELECT id FROM firms ORDER BY id
`

func (q *Queries) ListFirmIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFirmIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFirm = `-- name: UpdateFirm :one
UPDATE firms SET name = $1, brand_color = $2, updated_at = now()
WHERE id = $3
RETURNING id, name, brand_color, updated_at
`

type UpdateFirmParams struct {
	Name       string      `json:"name"`
	BrandColor pgtype.Text `json:"brand_color"`
	ID         uuid.UUID   `json:"id"`
}

type UpdateFirmRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	BrandColor pgtype.Text        `json:"brand_color"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Run inside WithFirm: the firms_update_own policy makes another Firm's row invisible (0 rows).
func (q *Queries) UpdateFirm(ctx context.Context, arg UpdateFirmParams) (UpdateFirmRow, error) {
	row := q.db.QueryRow(ctx, updateFirm, arg.Name, arg.BrandColor, arg.ID)
	var i UpdateFirmRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BrandColor,
		&i.UpdatedAt,
	)
	return i, err
}
