// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (firm_id, status, payload) VALUES ($1, 'uploaded', $2) RETURNING id, firm_id, status, payload, ruleset_version, issues, created_at, updated_at
`

type CreateInvoiceParams struct {
	FirmID  uuid.UUID `json:"firm_id"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice, arg.FirmID, arg.Payload)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Status,
		&i.Payload,
		&i.RulesetVersion,
		&i.Issues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, firm_id, status, payload, ruleset_version, issues, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Status,
		&i.Payload,
		&i.RulesetVersion,
		&i.Issues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoiceIDs = `-- name: ListInvoiceIDs :many
SELECT id FROM invoices ORDER BY created_at
`

func (q *Queries) ListInvoiceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listInvoiceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setValidation = `-- name: SetValidation :exec
UPDATE invoices SET status = $2, ruleset_version = $3, issues = $4, updated_at = now() WHERE id = $1
`

type SetValidationParams struct {
	ID             uuid.UUID   `json:"id"`
	Status         string      `json:"status"`
	RulesetVersion pgtype.Text `json:"ruleset_version"`
	Issues         []byte      `json:"issues"`
}

func (q *Queries) SetValidation(ctx context.Context, arg SetValidationParams) error {
	_, err := q.db.Exec(ctx, setValidation,
		arg.ID,
		arg.Status,
		arg.RulesetVersion,
		arg.Issues,
	)
	return err
}
