// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices_source.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentInvoices = `-- name: CountDocumentInvoices :one
SELECT count(*)::bigint FROM invoices WHERE document_id = $1
`

func (q *Queries) CountDocumentInvoices(ctx context.Context, documentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentInvoices, documentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertExtractedInvoice = `-- name: InsertExtractedInvoice :execrows
INSERT INTO invoices (firm_id, status, payload, client_company_id, document_id, source_ordinal, source_ref,
                      extraction_confidence, extraction_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
ON CONFLICT (document_id, source_ordinal) DO NOTHING
`

type InsertExtractedInvoiceParams struct {
	FirmID               uuid.UUID      `json:"firm_id"`
	Status               string         `json:"status"`
	Payload              []byte         `json:"payload"`
	ClientCompanyID      uuid.NullUUID  `json:"client_company_id"`
	DocumentID           uuid.NullUUID  `json:"document_id"`
	SourceOrdinal        pgtype.Int4    `json:"source_ordinal"`
	SourceRef            string         `json:"source_ref"`
	ExtractionConfidence pgtype.Numeric `json:"extraction_confidence"`
	ExtractionRunID      uuid.NullUUID  `json:"extraction_run_id"`
}

// Idempotent on (document_id, source_ordinal): a redelivered document.extracted inserts nothing.
func (q *Queries) InsertExtractedInvoice(ctx context.Context, arg InsertExtractedInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertExtractedInvoice,
		arg.FirmID,
		arg.Status,
		arg.Payload,
		arg.ClientCompanyID,
		arg.DocumentID,
		arg.SourceOrdinal,
		arg.SourceRef,
		arg.ExtractionConfidence,
		arg.ExtractionRunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDocumentInvoicesForPublish = `-- name: ListDocumentInvoicesForPublish :many
SELECT id, status, payload, extraction_confidence FROM invoices
WHERE document_id = $1
ORDER BY source_ordinal
`

type ListDocumentInvoicesForPublishRow struct {
	ID                   uuid.UUID      `json:"id"`
	Status               string         `json:"status"`
	Payload              []byte         `json:"payload"`
	ExtractionConfidence pgtype.Numeric `json:"extraction_confidence"`
}

func (q *Queries) ListDocumentInvoicesForPublish(ctx context.Context, documentID uuid.NullUUID) ([]ListDocumentInvoicesForPublishRow, error) {
	rows, err := q.db.Query(ctx, listDocumentInvoicesForPublish, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentInvoicesForPublishRow
	for rows.Next() {
		var i ListDocumentInvoicesForPublishRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Payload,
			&i.ExtractionConfidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reattributeDocumentInvoices = `-- name: ReattributeDocumentInvoices :execrows
UPDATE invoices SET client_company_id = $1, updated_at = now() WHERE document_id = $2
`

type ReattributeDocumentInvoicesParams struct {
	ClientCompanyID uuid.NullUUID `json:"client_company_id"`
	DocumentID      uuid.NullUUID `json:"document_id"`
}

func (q *Queries) ReattributeDocumentInvoices(ctx context.Context, arg ReattributeDocumentInvoicesParams) (int64, error) {
	result, err := q.db.Exec(ctx, reattributeDocumentInvoices, arg.ClientCompanyID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
