// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Firm struct {
	ID           uuid.UUID          `json:"id"`
	ZitadelOrgID string             `json:"zitadel_org_id"`
	Name         string             `json:"name"`
	BrandColor   pgtype.Text        `json:"brand_color"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID             uuid.UUID          `json:"id"`
	FirmID         uuid.UUID          `json:"firm_id"`
	Status         string             `json:"status"`
	Payload        []byte             `json:"payload"`
	RulesetVersion pgtype.Text        `json:"ruleset_version"`
	Issues         []byte             `json:"issues"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
