// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideProposal = `-- name: DecideProposal :one
UPDATE proposals
SET state = $1, decided_by = $2, decided_at = now(), decision_reason = $3,
    applied_at = $4
WHERE id = $5 AND state = 'proposed'
RETURNING id, firm_id, client_company_id, run_id, agent, kind, target_type, target_id, summary_key, summary_args, rationale, confidence, changes, detail_type, detail, evidence, state, decided_by, decided_at, decision_reason, applied_at, created_at, expires_at
`

type DecideProposalParams struct {
	State          string             `json:"state"`
	DecidedBy      pgtype.Text        `json:"decided_by"`
	DecisionReason pgtype.Text        `json:"decision_reason"`
	AppliedAt      pgtype.Timestamptz `json:"applied_at"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) DecideProposal(ctx context.Context, arg DecideProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, decideProposal,
		arg.State,
		arg.DecidedBy,
		arg.DecisionReason,
		arg.AppliedAt,
		arg.ID,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.RunID,
		&i.Agent,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.SummaryKey,
		&i.SummaryArgs,
		&i.Rationale,
		&i.Confidence,
		&i.Changes,
		&i.DetailType,
		&i.Detail,
		&i.Evidence,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const expireProposal = `-- name: ExpireProposal :execrows
UPDATE proposals SET state = 'expired' WHERE id = $1 AND state = 'proposed'
`

func (q *Queries) ExpireProposal(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expireProposal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProposal = `-- name: InsertProposal :execrows
INSERT INTO proposals (id, firm_id, client_company_id, run_id, agent, kind, target_type, target_id,
                       summary_key, summary_args, rationale, confidence, changes, detail_type, detail,
                       evidence, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13, $14, $15,
        $16, $17, $18)
ON CONFLICT (id) DO NOTHING
`

type InsertProposalParams struct {
	ID              uuid.UUID          `json:"id"`
	FirmID          uuid.UUID          `json:"firm_id"`
	ClientCompanyID uuid.NullUUID      `json:"client_company_id"`
	RunID           uuid.NullUUID      `json:"run_id"`
	Agent           string             `json:"agent"`
	Kind            string             `json:"kind"`
	TargetType      string             `json:"target_type"`
	TargetID        uuid.UUID          `json:"target_id"`
	SummaryKey      string             `json:"summary_key"`
	SummaryArgs     []byte             `json:"summary_args"`
	Rationale       string             `json:"rationale"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Changes         []byte             `json:"changes"`
	DetailType      string             `json:"detail_type"`
	Detail          []byte             `json:"detail"`
	Evidence        []byte             `json:"evidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProposal,
		arg.ID,
		arg.FirmID,
		arg.ClientCompanyID,
		arg.RunID,
		arg.Agent,
		arg.Kind,
		arg.TargetType,
		arg.TargetID,
		arg.SummaryKey,
		arg.SummaryArgs,
		arg.Rationale,
		arg.Confidence,
		arg.Changes,
		arg.DetailType,
		arg.Detail,
		arg.Evidence,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProposals = `-- name: ListProposals :many
SELECT id, firm_id, client_company_id, run_id, agent, kind, target_type, target_id, summary_key, summary_args, rationale, confidence, changes, detail_type, detail, evidence, state, decided_by, decided_at, decision_reason, applied_at, created_at, expires_at FROM proposals
WHERE ($1::text IS NULL OR state = $1::text)
  AND ($2::text IS NULL OR kind = $2::text)
  AND ($3::text IS NULL OR target_type = $3::text)
  AND ($4::uuid IS NULL OR target_id = $4::uuid)
  AND ($5::timestamptz IS NULL
       OR (created_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListProposalsParams struct {
	State           pgtype.Text        `json:"state"`
	Kind            pgtype.Text        `json:"kind"`
	TargetType      pgtype.Text        `json:"target_type"`
	TargetID        uuid.NullUUID      `json:"target_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        uuid.NullUUID      `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListProposals(ctx context.Context, arg ListProposalsParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listProposals,
		arg.State,
		arg.Kind,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientCompanyID,
			&i.RunID,
			&i.Agent,
			&i.Kind,
			&i.TargetType,
			&i.TargetID,
			&i.SummaryKey,
			&i.SummaryArgs,
			&i.Rationale,
			&i.Confidence,
			&i.Changes,
			&i.DetailType,
			&i.Detail,
			&i.Evidence,
			&i.State,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunProposals = `-- name: ListRunProposals :many
SELECT id, firm_id, client_company_id, run_id, agent, kind, target_type, target_id, summary_key, summary_args, rationale, confidence, changes, detail_type, detail, evidence, state, decided_by, decided_at, decision_reason, applied_at, created_at, expires_at FROM proposals WHERE run_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListRunProposals(ctx context.Context, runID uuid.NullUUID) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listRunProposals, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientCompanyID,
			&i.RunID,
			&i.Agent,
			&i.Kind,
			&i.TargetType,
			&i.TargetID,
			&i.SummaryKey,
			&i.SummaryArgs,
			&i.Rationale,
			&i.Confidence,
			&i.Changes,
			&i.DetailType,
			&i.Detail,
			&i.Evidence,
			&i.State,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProposal = `-- name: LockProposal :one
SELECT id, firm_id, client_company_id, run_id, agent, kind, target_type, target_id, summary_key, summary_args, rationale, confidence, changes, detail_type, detail, evidence, state, decided_by, decided_at, decision_reason, applied_at, created_at, expires_at FROM proposals WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProposal(ctx context.Context, id uuid.UUID) (Proposal, error) {
	row := q.db.QueryRow(ctx, lockProposal, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.RunID,
		&i.Agent,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.SummaryKey,
		&i.SummaryArgs,
		&i.Rationale,
		&i.Confidence,
		&i.Changes,
		&i.DetailType,
		&i.Detail,
		&i.Evidence,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const supersedeOpenProposals = `-- name: SupersedeOpenProposals :execrows
UPDATE proposals o SET state = 'superseded'
WHERE o.target_type = $1 AND o.target_id = $2 AND o.kind = $3 AND o.state = 'proposed'
  AND o.id <> $4
  AND NOT EXISTS (SELECT 1 FROM proposals p WHERE p.id = $4)
`

type SupersedeOpenProposalsParams struct {
	TargetType string    `json:"target_type"`
	TargetID   uuid.UUID `json:"target_id"`
	Kind       string    `json:"kind"`
	NewID      uuid.UUID `json:"new_id"`
}

// Runs before InsertProposal (the partial unique index allows one open proposal per target and kind).
// A redelivery of an existing proposal supersedes nothing.
func (q *Queries) SupersedeOpenProposals(ctx context.Context, arg SupersedeOpenProposalsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeOpenProposals,
		arg.TargetType,
		arg.TargetID,
		arg.Kind,
		arg.NewID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
