// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_invoices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const trackCApplyPayload = `-- name: TrackCApplyPayload :one
UPDATE invoices
SET payload                  = $1,
    payload_version          = payload_version + 1,
    status                   = 'fixed',
    approved_payload_version = NULL,
    approved_by              = NULL,
    approved_at              = NULL,
    updated_at               = now()
WHERE id = $2 AND payload_version = $3
RETURNING payload_version
`

type TrackCApplyPayloadParams struct {
	Payload                []byte    `json:"payload"`
	ID                     uuid.UUID `json:"id"`
	ExpectedPayloadVersion int32     `json:"expected_payload_version"`
}

// Stores a changed payload (invoicefix.Apply): next payload_version, status 'fixed', approval cleared.
// No row: the invoice is gone or its payload_version is no longer expected_payload_version.
func (q *Queries) TrackCApplyPayload(ctx context.Context, arg TrackCApplyPayloadParams) (int32, error) {
	row := q.db.QueryRow(ctx, trackCApplyPayload, arg.Payload, arg.ID, arg.ExpectedPayloadVersion)
	var payload_version int32
	err := row.Scan(&payload_version)
	return payload_version, err
}

const trackCApproveInvoice = `-- name: TrackCApproveInvoice :one
UPDATE invoices
SET status                   = 'ready',
    approved_payload_version = payload_version,
    approved_by              = $1::text,
    approved_at              = now(),
    updated_at               = now()
WHERE id = $2 AND status = 'validated' AND payload_version = $3
RETURNING payload_version, approved_at
`

type TrackCApproveInvoiceParams struct {
	ApprovedBy     string    `json:"approved_by"`
	ID             uuid.UUID `json:"id"`
	PayloadVersion int32     `json:"payload_version"`
}

type TrackCApproveInvoiceRow struct {
	PayloadVersion int32              `json:"payload_version"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
}

// Approves a clean invoice for export (spec §5.6.4): 'validated' at the given payload_version -> 'ready'.
// No row: the invoice is gone, not 'validated', or at another payload_version.
func (q *Queries) TrackCApproveInvoice(ctx context.Context, arg TrackCApproveInvoiceParams) (TrackCApproveInvoiceRow, error) {
	row := q.db.QueryRow(ctx, trackCApproveInvoice, arg.ApprovedBy, arg.ID, arg.PayloadVersion)
	var i TrackCApproveInvoiceRow
	err := row.Scan(&i.PayloadVersion, &i.ApprovedAt)
	return i, err
}

const trackCGetInvoice = `-- name: TrackCGetInvoice :one

SELECT id, status, payload, payload_version,
       COALESCE(latest_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS latest_run_id,
       approved_payload_version, approved_by, approved_at, ruleset_version, created_at, updated_at
FROM invoices
WHERE id = $1
`

type TrackCGetInvoiceRow struct {
	ID                     uuid.UUID          `json:"id"`
	Status                 string             `json:"status"`
	Payload                []byte             `json:"payload"`
	PayloadVersion         int32              `json:"payload_version"`
	LatestRunID            uuid.UUID          `json:"latest_run_id"`
	ApprovedPayloadVersion pgtype.Int4        `json:"approved_payload_version"`
	ApprovedBy             pgtype.Text        `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RulesetVersion         pgtype.Text        `json:"ruleset_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

// Track C invoice queries (spec §5.5, §5.6). Every query lists its columns (plan finding F11): Track B's
// migrations add invoice columns, and those must never change a Track C row type. Nullable uuid
// columns and parameters go through uuid.Nil (COALESCE / NULLIF) so that the generated Go types do not
// depend on sqlc's nullable-uuid override.
func (q *Queries) TrackCGetInvoice(ctx context.Context, id uuid.UUID) (TrackCGetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, trackCGetInvoice, id)
	var i TrackCGetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Payload,
		&i.PayloadVersion,
		&i.LatestRunID,
		&i.ApprovedPayloadVersion,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RulesetVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackCListFirmIDs = `-- name: TrackCListFirmIDs :many
SELECT id FROM firms ORDER BY id
`

// firms is a global table (no RLS): the sweeper and `api revalidate` iterate Firms with it.
func (q *Queries) TrackCListFirmIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, trackCListFirmIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackCListFixedInvoices = `-- name: TrackCListFixedInvoices :many
SELECT id, payload_version
FROM invoices
WHERE status = 'fixed' AND updated_at < $1
ORDER BY updated_at, id
LIMIT $2
`

type TrackCListFixedInvoicesParams struct {
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
	MaxRows       int32              `json:"max_rows"`
}

type TrackCListFixedInvoicesRow struct {
	ID             uuid.UUID `json:"id"`
	PayloadVersion int32     `json:"payload_version"`
}

// Sweeper (spec §5.6.2): invoices left in 'fixed' (re-validation pending) since before updated_before.
func (q *Queries) TrackCListFixedInvoices(ctx context.Context, arg TrackCListFixedInvoicesParams) ([]TrackCListFixedInvoicesRow, error) {
	rows, err := q.db.Query(ctx, trackCListFixedInvoices, arg.UpdatedBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListFixedInvoicesRow
	for rows.Next() {
		var i TrackCListFixedInvoicesRow
		if err := rows.Scan(&i.ID, &i.PayloadVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackCListInvoices = `-- name: TrackCListInvoices :many
SELECT i.id, i.status, i.payload_version,
       COALESCE(i.latest_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS latest_run_id,
       COALESCE(i.payload->>'invoice_number', '')::text AS invoice_number,
       COALESCE(i.payload->>'issue_date', '')::text AS issue_date,
       COALESCE(i.payload->>'invoice_type_code', '')::text AS invoice_type_code,
       COALESCE(i.payload->>'currency', '')::text AS currency,
       COALESCE(i.payload->>'total_amount', '')::text AS total_amount,
       COALESCE(i.payload->'seller'->>'name', '')::text AS seller_name,
       COALESCE(i.payload->'buyer'->>'name', '')::text AS buyer_name,
       COALESCE(r.error_count, 0)::integer AS error_count,
       COALESCE(r.warning_count, 0)::integer AS warning_count,
       i.created_at, i.updated_at
FROM invoices i
LEFT JOIN validation_runs r ON r.id = i.latest_run_id
WHERE ($1::text IS NULL OR i.status = $1::text)
  AND ($2::text IS NULL
       OR strpos(lower(COALESCE(i.payload->>'invoice_number', '')), lower($2::text)) > 0)
  AND ($3::timestamptz IS NULL
       OR (i.created_at, i.id) < ($3::timestamptz, $4::uuid))
ORDER BY i.created_at DESC, i.id DESC
LIMIT $5
`

type TrackCListInvoicesParams struct {
	Status          pgtype.Text        `json:"status"`
	Q               pgtype.Text        `json:"q"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        uuid.UUID          `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

type TrackCListInvoicesRow struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	PayloadVersion  int32              `json:"payload_version"`
	LatestRunID     uuid.UUID          `json:"latest_run_id"`
	InvoiceNumber   string             `json:"invoice_number"`
	IssueDate       string             `json:"issue_date"`
	InvoiceTypeCode string             `json:"invoice_type_code"`
	Currency        string             `json:"currency"`
	TotalAmount     string             `json:"total_amount"`
	SellerName      string             `json:"seller_name"`
	BuyerName       string             `json:"buyer_name"`
	ErrorCount      int32              `json:"error_count"`
	WarningCount    int32              `json:"warning_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// GET /v1/invoices (decision D-2): newest first, keyset cursor (before_created_at, before_id).
// q matches the invoice number as a case-insensitive substring (no LIKE wildcards). Money stays text.
func (q *Queries) TrackCListInvoices(ctx context.Context, arg TrackCListInvoicesParams) ([]TrackCListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, trackCListInvoices,
		arg.Status,
		arg.Q,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListInvoicesRow
	for rows.Next() {
		var i TrackCListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PayloadVersion,
			&i.LatestRunID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.InvoiceTypeCode,
			&i.Currency,
			&i.TotalAmount,
			&i.SellerName,
			&i.BuyerName,
			&i.ErrorCount,
			&i.WarningCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackCListInvoicesForRevalidation = `-- name: TrackCListInvoicesForRevalidation :many
SELECT i.id, i.status, r.id AS run_id, r.ruleset_version
FROM invoices i
JOIN validation_runs r ON r.id = i.latest_run_id
WHERE r.ruleset_version <> $1::text AND i.id > $2::uuid
ORDER BY i.id
LIMIT $3
`

type TrackCListInvoicesForRevalidationParams struct {
	RulesetVersion string    `json:"ruleset_version"`
	AfterID        uuid.UUID `json:"after_id"`
	MaxRows        int32     `json:"max_rows"`
}

type TrackCListInvoicesForRevalidationRow struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	RunID          uuid.UUID `json:"run_id"`
	RulesetVersion string    `json:"ruleset_version"`
}

// `api revalidate` (spec §5.6.2): invoices whose latest run used another RuleSet, in id order after
// after_id (pass uuid.Nil to start).
func (q *Queries) TrackCListInvoicesForRevalidation(ctx context.Context, arg TrackCListInvoicesForRevalidationParams) ([]TrackCListInvoicesForRevalidationRow, error) {
	rows, err := q.db.Query(ctx, trackCListInvoicesForRevalidation, arg.RulesetVersion, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListInvoicesForRevalidationRow
	for rows.Next() {
		var i TrackCListInvoicesForRevalidationRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.RunID,
			&i.RulesetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackCLockInvoice = `-- name: TrackCLockInvoice :one
SELECT id, status, payload, payload_version,
       COALESCE(latest_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS latest_run_id,
       approved_payload_version, approved_by, approved_at, ruleset_version, created_at, updated_at
FROM invoices
WHERE id = $1
FOR UPDATE
`

type TrackCLockInvoiceRow struct {
	ID                     uuid.UUID          `json:"id"`
	Status                 string             `json:"status"`
	Payload                []byte             `json:"payload"`
	PayloadVersion         int32              `json:"payload_version"`
	LatestRunID            uuid.UUID          `json:"latest_run_id"`
	ApprovedPayloadVersion pgtype.Int4        `json:"approved_payload_version"`
	ApprovedBy             pgtype.Text        `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	RulesetVersion         pgtype.Text        `json:"ruleset_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

// Same columns as TrackCGetInvoice, with the row locked until the transaction ends.
func (q *Queries) TrackCLockInvoice(ctx context.Context, id uuid.UUID) (TrackCLockInvoiceRow, error) {
	row := q.db.QueryRow(ctx, trackCLockInvoice, id)
	var i TrackCLockInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Payload,
		&i.PayloadVersion,
		&i.LatestRunID,
		&i.ApprovedPayloadVersion,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RulesetVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackCSetValidationResult = `-- name: TrackCSetValidationResult :execrows
UPDATE invoices
SET status                   = $1::text,
    latest_run_id            = $2::uuid,
    ruleset_version          = $3::text,
    issues                   = $4,
    approved_payload_version = CASE WHEN $1::text = 'ready' THEN approved_payload_version END,
    approved_by              = CASE WHEN $1::text = 'ready' THEN approved_by END,
    approved_at              = CASE WHEN $1::text = 'ready' THEN approved_at END,
    updated_at               = now()
WHERE id = $5 AND payload_version = $6
`

type TrackCSetValidationResultParams struct {
	Status         string    `json:"status"`
	RunID          uuid.UUID `json:"run_id"`
	RulesetVersion string    `json:"ruleset_version"`
	Issues         []byte    `json:"issues"`
	ID             uuid.UUID `json:"id"`
	PayloadVersion int32     `json:"payload_version"`
}

// Records a run's outcome on its invoice (spec §5.6.1 step 4), including the legacy ruleset_version and
// issues columns (Phase 0 IssueView shape). Any status other than 'ready' clears the approval.
// 0 rows: the invoice is gone or its payload_version changed.
func (q *Queries) TrackCSetValidationResult(ctx context.Context, arg TrackCSetValidationResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, trackCSetValidationResult,
		arg.Status,
		arg.RunID,
		arg.RulesetVersion,
		arg.Issues,
		arg.ID,
		arg.PayloadVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
