// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_validation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const trackCGetRun = `-- name: TrackCGetRun :one
SELECT id, invoice_id, payload_version, ruleset_version, trigger, error_count, warning_count, rules_evaluated,
       duration_us, requested_by, trace_id, created_at
FROM validation_runs
WHERE id = $1 AND invoice_id = $2
`

type TrackCGetRunParams struct {
	ID        uuid.UUID `json:"id"`
	InvoiceID uuid.UUID `json:"invoice_id"`
}

type TrackCGetRunRow struct {
	ID             uuid.UUID          `json:"id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	PayloadVersion int32              `json:"payload_version"`
	RulesetVersion string             `json:"ruleset_version"`
	Trigger        string             `json:"trigger"`
	ErrorCount     int32              `json:"error_count"`
	WarningCount   int32              `json:"warning_count"`
	RulesEvaluated int32              `json:"rules_evaluated"`
	DurationUs     int64              `json:"duration_us"`
	RequestedBy    string             `json:"requested_by"`
	TraceID        string             `json:"trace_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) TrackCGetRun(ctx context.Context, arg TrackCGetRunParams) (TrackCGetRunRow, error) {
	row := q.db.QueryRow(ctx, trackCGetRun, arg.ID, arg.InvoiceID)
	var i TrackCGetRunRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.PayloadVersion,
		&i.RulesetVersion,
		&i.Trigger,
		&i.ErrorCount,
		&i.WarningCount,
		&i.RulesEvaluated,
		&i.DurationUs,
		&i.RequestedBy,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const trackCInsertIssues = `-- name: TrackCInsertIssues :exec
INSERT INTO validation_issues (id, firm_id, run_id, invoice_id, seq, rule_id, severity, path, business_term,
                               message, message_ar, message_args, fixable, suggested_value)
SELECT gen_random_uuid(), $1::uuid, $2::uuid, $3::uuid,
       unnest($4::integer[]), unnest($5::text[]), unnest($6::text[]),
       unnest($7::text[]), unnest($8::text[]), unnest($9::text[]),
       unnest($10::text[]), unnest($11::text[])::jsonb, unnest($12::boolean[]),
       unnest($13::text[])
`

type TrackCInsertIssuesParams struct {
	FirmID          uuid.UUID `json:"firm_id"`
	RunID           uuid.UUID `json:"run_id"`
	InvoiceID       uuid.UUID `json:"invoice_id"`
	Seqs            []int32   `json:"seqs"`
	RuleIds         []string  `json:"rule_ids"`
	Severities      []string  `json:"severities"`
	Paths           []string  `json:"paths"`
	BusinessTerms   []string  `json:"business_terms"`
	Messages        []string  `json:"messages"`
	MessagesAr      []string  `json:"messages_ar"`
	MessageArgs     []string  `json:"message_args"`
	Fixables        []bool    `json:"fixables"`
	SuggestedValues []string  `json:"suggested_values"`
}

// All issues of one run in one statement. Plan finding F1: COPY FROM is not supported on a table with
// row-level security, so this is INSERT ... SELECT unnest(...), never :copyfrom. The arrays are parallel
// (element n of each is issue n; set-returning functions in one select list advance in lockstep, and a
// shorter array yields NULLs, which the NOT NULL columns reject). message_args elements are JSON object
// texts.
func (q *Queries) TrackCInsertIssues(ctx context.Context, arg TrackCInsertIssuesParams) error {
	_, err := q.db.Exec(ctx, trackCInsertIssues,
		arg.FirmID,
		arg.RunID,
		arg.InvoiceID,
		arg.Seqs,
		arg.RuleIds,
		arg.Severities,
		arg.Paths,
		arg.BusinessTerms,
		arg.Messages,
		arg.MessagesAr,
		arg.MessageArgs,
		arg.Fixables,
		arg.SuggestedValues,
	)
	return err
}

const trackCInsertRun = `-- name: TrackCInsertRun :one

INSERT INTO validation_runs (firm_id, invoice_id, payload_version, ruleset_version, trigger, error_count,
                             warning_count, rules_evaluated, duration_us, requested_by, trace_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
RETURNING id, created_at
`

type TrackCInsertRunParams struct {
	FirmID         uuid.UUID `json:"firm_id"`
	InvoiceID      uuid.UUID `json:"invoice_id"`
	PayloadVersion int32     `json:"payload_version"`
	RulesetVersion string    `json:"ruleset_version"`
	Trigger        string    `json:"trigger"`
	ErrorCount     int32     `json:"error_count"`
	WarningCount   int32     `json:"warning_count"`
	RulesEvaluated int32     `json:"rules_evaluated"`
	DurationUs     int64     `json:"duration_us"`
	RequestedBy    string    `json:"requested_by"`
	TraceID        string    `json:"trace_id"`
}

type TrackCInsertRunRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Track C validation runs and issues (spec §5.5, §5.6.1). Both tables are append-only.
func (q *Queries) TrackCInsertRun(ctx context.Context, arg TrackCInsertRunParams) (TrackCInsertRunRow, error) {
	row := q.db.QueryRow(ctx, trackCInsertRun,
		arg.FirmID,
		arg.InvoiceID,
		arg.PayloadVersion,
		arg.RulesetVersion,
		arg.Trigger,
		arg.ErrorCount,
		arg.WarningCount,
		arg.RulesEvaluated,
		arg.DurationUs,
		arg.RequestedBy,
		arg.TraceID,
	)
	var i TrackCInsertRunRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const trackCListIssues = `-- name: TrackCListIssues :many
SELECT id, seq, rule_id, severity, path, business_term, message, message_ar, message_args, fixable,
       suggested_value
FROM validation_issues
WHERE run_id = $1
ORDER BY seq
`

type TrackCListIssuesRow struct {
	ID             uuid.UUID `json:"id"`
	Seq            int32     `json:"seq"`
	RuleID         string    `json:"rule_id"`
	Severity       string    `json:"severity"`
	Path           string    `json:"path"`
	BusinessTerm   string    `json:"business_term"`
	Message        string    `json:"message"`
	MessageAr      string    `json:"message_ar"`
	MessageArgs    []byte    `json:"message_args"`
	Fixable        bool      `json:"fixable"`
	SuggestedValue string    `json:"suggested_value"`
}

// A run's issues in issue order (seq).
func (q *Queries) TrackCListIssues(ctx context.Context, runID uuid.UUID) ([]TrackCListIssuesRow, error) {
	rows, err := q.db.Query(ctx, trackCListIssues, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListIssuesRow
	for rows.Next() {
		var i TrackCListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RuleID,
			&i.Severity,
			&i.Path,
			&i.BusinessTerm,
			&i.Message,
			&i.MessageAr,
			&i.MessageArgs,
			&i.Fixable,
			&i.SuggestedValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackCListRuns = `-- name: TrackCListRuns :many
SELECT id, invoice_id, payload_version, ruleset_version, trigger, error_count, warning_count, rules_evaluated,
       duration_us, requested_by, trace_id, created_at
FROM validation_runs
WHERE invoice_id = $1
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type TrackCListRunsParams struct {
	InvoiceID       uuid.UUID          `json:"invoice_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        uuid.UUID          `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

type TrackCListRunsRow struct {
	ID             uuid.UUID          `json:"id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	PayloadVersion int32              `json:"payload_version"`
	RulesetVersion string             `json:"ruleset_version"`
	Trigger        string             `json:"trigger"`
	ErrorCount     int32              `json:"error_count"`
	WarningCount   int32              `json:"warning_count"`
	RulesEvaluated int32              `json:"rules_evaluated"`
	DurationUs     int64              `json:"duration_us"`
	RequestedBy    string             `json:"requested_by"`
	TraceID        string             `json:"trace_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// An invoice's runs, newest first, keyset cursor (before_created_at, before_id). With a run's
// (created_at, id) as the cursor and page_limit 1 this is the run before it (the diff default).
func (q *Queries) TrackCListRuns(ctx context.Context, arg TrackCListRunsParams) ([]TrackCListRunsRow, error) {
	rows, err := q.db.Query(ctx, trackCListRuns,
		arg.InvoiceID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListRunsRow
	for rows.Next() {
		var i TrackCListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.PayloadVersion,
			&i.RulesetVersion,
			&i.Trigger,
			&i.ErrorCount,
			&i.WarningCount,
			&i.RulesEvaluated,
			&i.DurationUs,
			&i.RequestedBy,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
