// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_proposals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const trackCGetProposal = `-- name: TrackCGetProposal :one

SELECT id, firm_id, client_company_id, run_id, agent, kind, target_type, target_id, summary_key, summary_args, rationale, confidence, changes, detail_type, detail, evidence, state, decided_by, decided_at, decision_reason, applied_at, created_at, expires_at FROM proposals WHERE id = $1
`

// Track C read of one proposal for GET /v1/proposals/{id} (a plain read: LockProposal is FOR UPDATE and
// belongs to proposals.Decide). Added with Task 19; Track B's proposals.sql stays untouched.
func (q *Queries) TrackCGetProposal(ctx context.Context, id uuid.UUID) (Proposal, error) {
	row := q.db.QueryRow(ctx, trackCGetProposal, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientCompanyID,
		&i.RunID,
		&i.Agent,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.SummaryKey,
		&i.SummaryArgs,
		&i.Rationale,
		&i.Confidence,
		&i.Changes,
		&i.DetailType,
		&i.Detail,
		&i.Evidence,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
