// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const trackCInsertAuditEvent = `-- name: TrackCInsertAuditEvent :one

INSERT INTO audit_events (firm_id, actor_type, actor_id, agent, proposal_id, action, entity_type, entity_id,
                          invoice_id, changes, before, after, reason, trace_id)
VALUES ($1, $2, $3, $4,
        NULLIF($5::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
        $6, $7, $8,
        NULLIF($9::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
        $10, $11, $12, $13, $14)
RETURNING id, occurred_at
`

type TrackCInsertAuditEventParams struct {
	FirmID     uuid.UUID `json:"firm_id"`
	ActorType  string    `json:"actor_type"`
	ActorID    string    `json:"actor_id"`
	Agent      string    `json:"agent"`
	ProposalID uuid.UUID `json:"proposal_id"`
	Action     string    `json:"action"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	InvoiceID  uuid.UUID `json:"invoice_id"`
	Changes    []byte    `json:"changes"`
	Before     []byte    `json:"before"`
	After      []byte    `json:"after"`
	Reason     string    `json:"reason"`
	TraceID    string    `json:"trace_id"`
}

type TrackCInsertAuditEventRow struct {
	ID         uuid.UUID          `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// Track C audit events (spec §5.5, §5.6.3). Append-only. proposal_id and invoice_id are nullable;
// uuid.Nil stands for NULL in both directions.
func (q *Queries) TrackCInsertAuditEvent(ctx context.Context, arg TrackCInsertAuditEventParams) (TrackCInsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, trackCInsertAuditEvent,
		arg.FirmID,
		arg.ActorType,
		arg.ActorID,
		arg.Agent,
		arg.ProposalID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.InvoiceID,
		arg.Changes,
		arg.Before,
		arg.After,
		arg.Reason,
		arg.TraceID,
	)
	var i TrackCInsertAuditEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const trackCListInvoiceAudit = `-- name: TrackCListInvoiceAudit :many
SELECT id, occurred_at, actor_type, actor_id, agent,
       COALESCE(proposal_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS proposal_id,
       action, entity_type, entity_id, changes, before, after, reason, trace_id
FROM audit_events
WHERE invoice_id = $1::uuid
  AND ($2::timestamptz IS NULL
       OR (occurred_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type TrackCListInvoiceAuditParams struct {
	InvoiceID        uuid.UUID          `json:"invoice_id"`
	BeforeOccurredAt pgtype.Timestamptz `json:"before_occurred_at"`
	BeforeID         uuid.UUID          `json:"before_id"`
	PageLimit        int32              `json:"page_limit"`
}

type TrackCListInvoiceAuditRow struct {
	ID         uuid.UUID          `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	Agent      string             `json:"agent"`
	ProposalID uuid.UUID          `json:"proposal_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Reason     string             `json:"reason"`
	TraceID    string             `json:"trace_id"`
}

// An invoice's audit trail, newest first, keyset cursor (before_occurred_at, before_id).
func (q *Queries) TrackCListInvoiceAudit(ctx context.Context, arg TrackCListInvoiceAuditParams) ([]TrackCListInvoiceAuditRow, error) {
	rows, err := q.db.Query(ctx, trackCListInvoiceAudit,
		arg.InvoiceID,
		arg.BeforeOccurredAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListInvoiceAuditRow
	for rows.Next() {
		var i TrackCListInvoiceAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorType,
			&i.ActorID,
			&i.Agent,
			&i.ProposalID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Before,
			&i.After,
			&i.Reason,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
