// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_fix_tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const trackCCompleteFixTask = `-- name: TrackCCompleteFixTask :execrows
UPDATE fix_tasks
SET status       = $1,
    outcome      = $2,
    proposal_id  = NULLIF($3::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
    agent_run_id = NULLIF($4::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
    error_code   = $5,
    completed_at = clock_timestamp()
WHERE id = $6 AND status = 'requested'
`

type TrackCCompleteFixTaskParams struct {
	Status     string    `json:"status"`
	Outcome    string    `json:"outcome"`
	ProposalID uuid.UUID `json:"proposal_id"`
	AgentRunID uuid.UUID `json:"agent_run_id"`
	ErrorCode  string    `json:"error_code"`
	ID         uuid.UUID `json:"id"`
}

// requested -> terminal with the agent's result. 0 rows: unknown task or already terminal (a duplicate).
func (q *Queries) TrackCCompleteFixTask(ctx context.Context, arg TrackCCompleteFixTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, trackCCompleteFixTask,
		arg.Status,
		arg.Outcome,
		arg.ProposalID,
		arg.AgentRunID,
		arg.ErrorCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trackCGetFixTask = `-- name: TrackCGetFixTask :one
SELECT id, invoice_id, run_id, mode, status, outcome,
       COALESCE(proposal_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS proposal_id,
       COALESCE(agent_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS agent_run_id,
       error_code, requested_by, requested_at, published_at, completed_at
FROM fix_tasks
WHERE id = $1
`

type TrackCGetFixTaskRow struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	RunID       uuid.UUID          `json:"run_id"`
	Mode        string             `json:"mode"`
	Status      string             `json:"status"`
	Outcome     string             `json:"outcome"`
	ProposalID  uuid.UUID          `json:"proposal_id"`
	AgentRunID  uuid.UUID          `json:"agent_run_id"`
	ErrorCode   string             `json:"error_code"`
	RequestedBy string             `json:"requested_by"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) TrackCGetFixTask(ctx context.Context, id uuid.UUID) (TrackCGetFixTaskRow, error) {
	row := q.db.QueryRow(ctx, trackCGetFixTask, id)
	var i TrackCGetFixTaskRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.Mode,
		&i.Status,
		&i.Outcome,
		&i.ProposalID,
		&i.AgentRunID,
		&i.ErrorCode,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.PublishedAt,
		&i.CompletedAt,
	)
	return i, err
}

const trackCGetFixTaskByRunMode = `-- name: TrackCGetFixTaskByRunMode :one
SELECT id, invoice_id, run_id, mode, status, outcome,
       COALESCE(proposal_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS proposal_id,
       COALESCE(agent_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS agent_run_id,
       error_code, requested_by, requested_at, published_at, completed_at
FROM fix_tasks
WHERE run_id = $1 AND mode = $2
`

type TrackCGetFixTaskByRunModeParams struct {
	RunID uuid.UUID `json:"run_id"`
	Mode  string    `json:"mode"`
}

type TrackCGetFixTaskByRunModeRow struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	RunID       uuid.UUID          `json:"run_id"`
	Mode        string             `json:"mode"`
	Status      string             `json:"status"`
	Outcome     string             `json:"outcome"`
	ProposalID  uuid.UUID          `json:"proposal_id"`
	AgentRunID  uuid.UUID          `json:"agent_run_id"`
	ErrorCode   string             `json:"error_code"`
	RequestedBy string             `json:"requested_by"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) TrackCGetFixTaskByRunMode(ctx context.Context, arg TrackCGetFixTaskByRunModeParams) (TrackCGetFixTaskByRunModeRow, error) {
	row := q.db.QueryRow(ctx, trackCGetFixTaskByRunMode, arg.RunID, arg.Mode)
	var i TrackCGetFixTaskByRunModeRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.Mode,
		&i.Status,
		&i.Outcome,
		&i.ProposalID,
		&i.AgentRunID,
		&i.ErrorCode,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.PublishedAt,
		&i.CompletedAt,
	)
	return i, err
}

const trackCInsertFixTask = `-- name: TrackCInsertFixTask :execrows

INSERT INTO fix_tasks (id, firm_id, invoice_id, run_id, mode, requested_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (run_id, mode) DO NOTHING
`

type TrackCInsertFixTaskParams struct {
	ID          uuid.UUID `json:"id"`
	FirmID      uuid.UUID `json:"firm_id"`
	InvoiceID   uuid.UUID `json:"invoice_id"`
	RunID       uuid.UUID `json:"run_id"`
	Mode        string    `json:"mode"`
	RequestedBy string    `json:"requested_by"`
}

// Track C Fix agent tasks (spec §5.5, §5.6.8). The fix_tasks_guard trigger allows publishing while
// 'requested' and one requested -> terminal update. proposal_id and agent_run_id are nullable;
// uuid.Nil stands for NULL in both directions.
// Idempotent on (run_id, mode): 0 rows means the task exists (read it with TrackCGetFixTaskByRunMode).
func (q *Queries) TrackCInsertFixTask(ctx context.Context, arg TrackCInsertFixTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, trackCInsertFixTask,
		arg.ID,
		arg.FirmID,
		arg.InvoiceID,
		arg.RunID,
		arg.Mode,
		arg.RequestedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trackCLatestFixTask = `-- name: TrackCLatestFixTask :one
SELECT id, invoice_id, run_id, mode, status, outcome,
       COALESCE(proposal_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS proposal_id,
       COALESCE(agent_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS agent_run_id,
       error_code, requested_by, requested_at, published_at, completed_at
FROM fix_tasks
WHERE invoice_id = $1
ORDER BY requested_at DESC, id DESC
LIMIT 1
`

type TrackCLatestFixTaskRow struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	RunID       uuid.UUID          `json:"run_id"`
	Mode        string             `json:"mode"`
	Status      string             `json:"status"`
	Outcome     string             `json:"outcome"`
	ProposalID  uuid.UUID          `json:"proposal_id"`
	AgentRunID  uuid.UUID          `json:"agent_run_id"`
	ErrorCode   string             `json:"error_code"`
	RequestedBy string             `json:"requested_by"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// The invoice's most recent task (invoice detail; fix_in_progress check).
func (q *Queries) TrackCLatestFixTask(ctx context.Context, invoiceID uuid.UUID) (TrackCLatestFixTaskRow, error) {
	row := q.db.QueryRow(ctx, trackCLatestFixTask, invoiceID)
	var i TrackCLatestFixTaskRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.Mode,
		&i.Status,
		&i.Outcome,
		&i.ProposalID,
		&i.AgentRunID,
		&i.ErrorCode,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.PublishedAt,
		&i.CompletedAt,
	)
	return i, err
}

const trackCListUnpublishedFixTasks = `-- name: TrackCListUnpublishedFixTasks :many
SELECT id, invoice_id, run_id, mode, status, outcome,
       COALESCE(proposal_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS proposal_id,
       COALESCE(agent_run_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS agent_run_id,
       error_code, requested_by, requested_at, published_at, completed_at
FROM fix_tasks
WHERE status = 'requested' AND published_at IS NULL AND requested_at < $1
ORDER BY requested_at, id
LIMIT $2
`

type TrackCListUnpublishedFixTasksParams struct {
	RequestedBefore pgtype.Timestamptz `json:"requested_before"`
	MaxRows         int32              `json:"max_rows"`
}

type TrackCListUnpublishedFixTasksRow struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	RunID       uuid.UUID          `json:"run_id"`
	Mode        string             `json:"mode"`
	Status      string             `json:"status"`
	Outcome     string             `json:"outcome"`
	ProposalID  uuid.UUID          `json:"proposal_id"`
	AgentRunID  uuid.UUID          `json:"agent_run_id"`
	ErrorCode   string             `json:"error_code"`
	RequestedBy string             `json:"requested_by"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// Sweeper: requested tasks whose publish never succeeded, requested before requested_before.
func (q *Queries) TrackCListUnpublishedFixTasks(ctx context.Context, arg TrackCListUnpublishedFixTasksParams) ([]TrackCListUnpublishedFixTasksRow, error) {
	rows, err := q.db.Query(ctx, trackCListUnpublishedFixTasks, arg.RequestedBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListUnpublishedFixTasksRow
	for rows.Next() {
		var i TrackCListUnpublishedFixTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.RunID,
			&i.Mode,
			&i.Status,
			&i.Outcome,
			&i.ProposalID,
			&i.AgentRunID,
			&i.ErrorCode,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.PublishedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackCMarkFixTaskPublished = `-- name: TrackCMarkFixTaskPublished :execrows
UPDATE fix_tasks SET published_at = now() WHERE id = $1 AND status = 'requested'
`

func (q *Queries) TrackCMarkFixTaskPublished(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, trackCMarkFixTaskPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trackCTimeOutFixTasks = `-- name: TrackCTimeOutFixTasks :many
UPDATE fix_tasks
SET status = 'failed', error_code = 'timeout', completed_at = clock_timestamp()
WHERE status = 'requested' AND requested_at < $1
RETURNING id, invoice_id
`

type TrackCTimeOutFixTasksRow struct {
	ID        uuid.UUID `json:"id"`
	InvoiceID uuid.UUID `json:"invoice_id"`
}

// Sweeper: closes tasks still 'requested' since before requested_before as failed/timeout.
func (q *Queries) TrackCTimeOutFixTasks(ctx context.Context, requestedBefore pgtype.Timestamptz) ([]TrackCTimeOutFixTasksRow, error) {
	rows, err := q.db.Query(ctx, trackCTimeOutFixTasks, requestedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCTimeOutFixTasksRow
	for rows.Next() {
		var i TrackCTimeOutFixTasksRow
		if err := rows.Scan(&i.ID, &i.InvoiceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
