// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_exports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const trackCGetExport = `-- name: TrackCGetExport :one
SELECT x.id, x.invoice_id, x.run_id, x.payload_version, x.ruleset_version, x.format, x.document_kind,
       x.object_key, x.sha256, x.size_bytes, x.created_by, x.created_at,
       COALESCE(i.payload->>'invoice_number', '')::text AS invoice_number
FROM exports x
JOIN invoices i ON i.id = x.invoice_id
WHERE x.id = $1
`

type TrackCGetExportRow struct {
	ID             uuid.UUID          `json:"id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	RunID          uuid.UUID          `json:"run_id"`
	PayloadVersion int32              `json:"payload_version"`
	RulesetVersion string             `json:"ruleset_version"`
	Format         string             `json:"format"`
	DocumentKind   string             `json:"document_kind"`
	ObjectKey      string             `json:"object_key"`
	Sha256         string             `json:"sha256"`
	SizeBytes      int32              `json:"size_bytes"`
	CreatedBy      string             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	InvoiceNumber  string             `json:"invoice_number"`
}

// invoice_number is the invoice's current number (for the download filename).
func (q *Queries) TrackCGetExport(ctx context.Context, id uuid.UUID) (TrackCGetExportRow, error) {
	row := q.db.QueryRow(ctx, trackCGetExport, id)
	var i TrackCGetExportRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PayloadVersion,
		&i.RulesetVersion,
		&i.Format,
		&i.DocumentKind,
		&i.ObjectKey,
		&i.Sha256,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.InvoiceNumber,
	)
	return i, err
}

const trackCInsertExport = `-- name: TrackCInsertExport :one

INSERT INTO exports (id, firm_id, invoice_id, run_id, payload_version, ruleset_version, format, document_kind,
                     object_key, sha256, size_bytes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12)
RETURNING created_at
`

type TrackCInsertExportParams struct {
	ID             uuid.UUID `json:"id"`
	FirmID         uuid.UUID `json:"firm_id"`
	InvoiceID      uuid.UUID `json:"invoice_id"`
	RunID          uuid.UUID `json:"run_id"`
	PayloadVersion int32     `json:"payload_version"`
	RulesetVersion string    `json:"ruleset_version"`
	Format         string    `json:"format"`
	DocumentKind   string    `json:"document_kind"`
	ObjectKey      string    `json:"object_key"`
	Sha256         string    `json:"sha256"`
	SizeBytes      int32     `json:"size_bytes"`
	CreatedBy      string    `json:"created_by"`
}

// Track C exports (spec §5.5, §5.6.5). Append-only; object_key is checked by exports_object_key_shape.
func (q *Queries) TrackCInsertExport(ctx context.Context, arg TrackCInsertExportParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, trackCInsertExport,
		arg.ID,
		arg.FirmID,
		arg.InvoiceID,
		arg.RunID,
		arg.PayloadVersion,
		arg.RulesetVersion,
		arg.Format,
		arg.DocumentKind,
		arg.ObjectKey,
		arg.Sha256,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const trackCListExports = `-- name: TrackCListExports :many
SELECT x.id, x.invoice_id, x.run_id, x.payload_version, x.ruleset_version, x.format, x.document_kind,
       x.object_key, x.sha256, x.size_bytes, x.created_by, x.created_at,
       COALESCE(i.payload->>'invoice_number', '')::text AS invoice_number
FROM exports x
JOIN invoices i ON i.id = x.invoice_id
WHERE x.invoice_id = $1
ORDER BY x.created_at DESC, x.id DESC
`

type TrackCListExportsRow struct {
	ID             uuid.UUID          `json:"id"`
	InvoiceID      uuid.UUID          `json:"invoice_id"`
	RunID          uuid.UUID          `json:"run_id"`
	PayloadVersion int32              `json:"payload_version"`
	RulesetVersion string             `json:"ruleset_version"`
	Format         string             `json:"format"`
	DocumentKind   string             `json:"document_kind"`
	ObjectKey      string             `json:"object_key"`
	Sha256         string             `json:"sha256"`
	SizeBytes      int32              `json:"size_bytes"`
	CreatedBy      string             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	InvoiceNumber  string             `json:"invoice_number"`
}

// An invoice's exports, newest first.
func (q *Queries) TrackCListExports(ctx context.Context, invoiceID uuid.UUID) ([]TrackCListExportsRow, error) {
	rows, err := q.db.Query(ctx, trackCListExports, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCListExportsRow
	for rows.Next() {
		var i TrackCListExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.RunID,
			&i.PayloadVersion,
			&i.RulesetVersion,
			&i.Format,
			&i.DocumentKind,
			&i.ObjectKey,
			&i.Sha256,
			&i.SizeBytes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.InvoiceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
