// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackc_fix_tasks_context.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const trackCFixInvoiceContext = `-- name: TrackCFixInvoiceContext :one

SELECT COALESCE(client_company_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS client_company_id
FROM invoices
WHERE id = $1
`

// Task 20, plan finding F14: AgentTaskRequested.client_company_id comes from Track B's
// invoices.client_company_id (migration 00013). The column is nullable; uuid.Nil stands for NULL.
func (q *Queries) TrackCFixInvoiceContext(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, trackCFixInvoiceContext, id)
	var client_company_id uuid.UUID
	err := row.Scan(&client_company_id)
	return client_company_id, err
}
